name: Test application with Java CI and Gradle


on:
  push:
    branches:
      - "dev-*"

    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - "main"

    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
      - '.github/workflows/**'


jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GHA_EVENT: ${{ github.event_name }}
      GH_COMMIT_HASH: ${{ github.sha }}

      GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew build test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build/libs/
